### ISSUE TITLE
Feature Request: Similar fuctionality for Drive/Docs layout 

### ISSUE THREAD

**Issue by MichaelTene7** [nuchi/gmail-inbox-high-contrast-restoration#2]
Apologies that this is likely a request to make basically a new filterlist. 
I was wondering if it would be possible for you to do a similar thing for google docs/google drive -- a very similar change has been rolled out to the various drive-suite editors (eg. docs, slides). I really like the functionality of this list on gmail, and wanted to know if it would be possible to have similar features on docs/drive.

**Comment by nuchi** [comment]
I definitely sympathize but I won't make that. I don't use docs/slides/drive enough to have formed an attachment to the old UI, so it's just not important enough to me to spend the time and effort.

I would definitely be happy to see someone else go and make it, however! I'd expect it to be much easier than the gmail version, since most of the work that went into the gmail list was around getting it compatible with all the themes, and docs/etc doesn't (to my knowledge) support multiple themes.
